# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pneus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pneus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpneus.proto\x12\x05pneus\"w\n\tDadosPneu\x12\x10\n\x08\x63\x61rro_id\x18\x01 \x01(\x05\x12\x0f\n\x07pressao\x18\x02 \x01(\x02\x12\x13\n\x0btemperatura\x18\x03 \x01(\x02\x12\x10\n\x08\x64\x65sgaste\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\r\n\x05volta\x18\x06 \x01(\x05\":\n\x15RespostaArmazenamento\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2R\n\x0bPneuStorage\x12\x43\n\x0f\x45nviarDadosPneu\x12\x10.pneus.DadosPneu\x1a\x1c.pneus.RespostaArmazenamento\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pneus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DADOSPNEU']._serialized_start=22
  _globals['_DADOSPNEU']._serialized_end=141
  _globals['_RESPOSTAARMAZENAMENTO']._serialized_start=143
  _globals['_RESPOSTAARMAZENAMENTO']._serialized_end=201
  _globals['_PNEUSTORAGE']._serialized_start=203
  _globals['_PNEUSTORAGE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
